apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab2
  labels:
    app: devops-lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab2
  template:
    metadata:
      labels:
        app: devops-lab2
    spec:
      containers:
        - name: placeholder
          image: alpine:3.22
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
